import App from "xprt/app";
export default {
    previousMonth : App.locX('/month/prev_month'),
    nextMonth     : App.locX('/month/next_month'),
    months        : [App.locX('/month/1'),
    App.locX('/month/2'),
    App.locX('/month/3'),
    App.locX('/month/4'),
    App.locX('/month/5'),
    App.locX('/month/6'),
    App.locX('/month/7'),
    App.locX('/month/8'),
    App.locX('/month/9'),
    App.locX('/month/10'),
    App.locX('/month/11'),
    App.locX('/month/12')],
    weekdays      : [App.locX('/day/l0'),
    App.locX('/day/l1'),
    App.locX('/day/l2'),
    App.locX('/day/l3'),
    App.locX('/day/l4'),
    App.locX('/day/l5'),
    App.locX('/day/l6')],
    weekdaysShort : [App.locX('/day/s0'),
    App.locX('/day/s1'),
    App.locX('/day/s2'),
    App.locX('/day/s3'),
    App.locX('/day/s4'),
    App.locX('/day/s5'),
    App.locX('/day/s6')]
};
